/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;


public class MenuView extends javax.swing.JFrame {   

    
     
    public MenuView() {
        initComponents();
        this.setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
<<<<<<< Updated upstream
        menuAlumnos = new javax.swing.JMenu();
        menuFormularioAlumnos = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        menuFormularioMateriaa = new javax.swing.JMenuItem();
        menuAdministracion = new javax.swing.JMenu();
        menuConsulta = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();
=======
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
>>>>>>> Stashed changes

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
<<<<<<< Updated upstream
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        menuAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/colegial.png"))); // NOI18N
        menuAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnosActionPerformed(evt);
            }
        });

        menuFormularioAlumnos.setText("Formulario de Alumnos");
        menuFormularioAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormularioAlumnosActionPerformed(evt);
            }
        });
        menuAlumnos.add(menuFormularioAlumnos);

        jMenuBar1.add(menuAlumnos);
=======
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/alumno (1)_1.png"))); // NOI18N

        jMenuItem1.setText("Formulario de Alumno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/pila-de-libros-de-tres_1.png"))); // NOI18N

        jMenuItem2.setText("Formulario de Materia");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/archivo-de-base-de-datos_1.png"))); // NOI18N

        jMenuItem3.setText("Formulario de Inscripción");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem3);

        jMenuBar1.add(jMenu9);
>>>>>>> Stashed changes

        menuMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/libros.png"))); // NOI18N
        menuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMateriaActionPerformed(evt);
            }
        });

        menuFormularioMateriaa.setText("Formulario de Materia");
        menuFormularioMateriaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormularioMateriaaActionPerformed(evt);
            }
        });
        menuMateria.add(menuFormularioMateriaa);

        jMenuBar1.add(menuMateria);

        menuAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/administracion.png"))); // NOI18N
        jMenuBar1.add(menuAdministracion);

        menuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/consulta.png"))); // NOI18N
        jMenuBar1.add(menuConsulta);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salida.png"))); // NOI18N
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< Updated upstream
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
=======
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< Updated upstream

    private void menuFormularioAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormularioAlumnosActionPerformed
       escritorio.removeAll();
       escritorio.repaint();
       FormularioAlumnoView alumno=new FormularioAlumnoView();
       alumno.setVisible(true);
       alumno.getContentPane().setBackground(Color.BLUE);
       escritorio.add(alumno);
       
    }//GEN-LAST:event_menuFormularioAlumnosActionPerformed

    private void menuFormularioMateriaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormularioMateriaaActionPerformed
       escritorio.removeAll();
       escritorio.repaint();
       FormularioMateria materia=new FormularioMateria();
       materia.setVisible(true);
       materia.getContentPane().setBackground(Color.BLUE);
       escritorio.add(materia);
    }//GEN-LAST:event_menuFormularioMateriaaActionPerformed

    private void menuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMateriaActionPerformed

    private void menuAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAlumnosActionPerformed

    private void menuFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuFormularioMateriaActionPerformed
       escritorio.removeAll();
       escritorio.repaint();
       FormularioAlumnoView alumno=new FormularioAlumnoView();
       alumno.setVisible(true);
       alumno.getContentPane().setBackground(Color.BLUE);
       escritorio.add(alumno);
    }//GEN-LAST:event_jmenuFormularioMateriaActionPerformed


=======
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       jDesktopPane1.removeAll();
       jDesktopPane1.repaint();
       FormularioAlumnoView alumno=new FormularioAlumnoView();
       alumno.setVisible(true);
       alumno.getContentPane().setBackground(Color.BLUE);
       jDesktopPane1.add(alumno);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       jDesktopPane1.removeAll();
       jDesktopPane1.repaint();
       FormularioAlumnoView alumno=new FormularioAlumnoView();
       alumno.setVisible(true);
       alumno.getContentPane().setBackground(Color.BLUE);
       jDesktopPane1.add(alumno);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       
    }//GEN-LAST:event_jMenuItem3ActionPerformed
>>>>>>> Stashed changes

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
<<<<<<< Updated upstream
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuFormularioAlumnos;
    private javax.swing.JMenuItem menuFormularioMateriaa;
    private javax.swing.JMenu menuMateria;
    private javax.swing.JMenu menuSalir;
=======
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
>>>>>>> Stashed changes
    // End of variables declaration//GEN-END:variables
}
